spring:
  datasource:
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}
    initialization-mode: always

#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:lvlz1sTest
#    username: sa
#    password:

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 15MB
      file-size-threshold: 1MB
# https://docs.spring.io/spring-boot/docs/2.1.18.RELEASE/reference/html/howto-database-initialization.html