spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:lvlz1sTest
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 15MB
      file-size-threshold: 1MB
# https://docs.spring.io/spring-boot/docs/2.1.18.RELEASE/reference/html/howto-database-initialization.html